In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

#Read CSV FIle
data = pd.read_csv("income.csv")

data = pd.read_csv("income.csv", na_values=[' ?'])
print(data.isnull().sum())

missing=data[data.isnull().any(axis=1)]
data1=data.dropna(axis=0)

data1['salstat']=data['salstat'].map({' <=50K':0, " >50K":1})
new_data = pd.get_dummies(data1,drop_first=True)

columns_list=list(new_data.columns)
#features=columns_list[0:4]+columns_list[5:]
features=list(set(columns_list)-set(['salstat']))

x=new_data[features].values
y=new_data['salstat'].values

train_x, test_x, train_y, test_y=train_test_split(x,y,test_size=0.4)

l=LogisticRegression(max_iter = 20000)
l.fit(train_x, train_y)
predict2=l.predict(test_x)
cm=confusion_matrix(test_y, predict2)
a=accuracy_score(test_y, predict2)
print("Accuracy",str(a))
print((test_y!=predict2).sum())

Age                  0
JobType           1836
EdType               0
Marital Status       0
Occupation        1843
relationship         0
race                 0
gender               0
capitalgain          0
capitalloss          0
hoursperweek         0
nativecountry      583
salstat              0
dtype: int64
Accuracy 0.8462494819726482
1855

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             32561 non-null  int64
 1   JobType         30725 non-null  object
 2   EdType          32561 non-null  object
 3   Marital Status  32561 non-null  object
 4   Occupation      30718 non-null  object
 5   relationship    32561 non-null  object
 6   race            32561 non-null  object
 7   gender          32561 non-null  object
 8   capitalgain     32561 non-null  int64
 9   capitalloss     32561 non-null  int64
 10  hoursperweek    32561 non-null  int64
 11  nativecountry   31978 non-null  object
 12  salstat         32561 non-null  object
dtypes: int64(4), object(9)
memory usage: 3.2+ MB

In [3]:
df=pd.read_csv('kddcup99_csv (1).csv')

In [4]:
df

,duration,protocol_type,service,flag,src_bytes,dst_bytes,attack,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,tcp,http,SF,181,5450,0,0,0,0,...,9,1.0,0.0,0.11,0.00,0.00,0.00,0.0,0.0,normal
1,0,tcp,http,SF,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.00,0.00,0.00,0.0,0.0,normal
2,0,tcp,http,SF,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.00,0.00,0.00,0.0,0.0,normal
3,0,tcp,http,SF,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.00,0.00,0.00,0.0,0.0,normal
4,0,tcp,http,SF,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.00,0.00,0.00,0.0,0.0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494015,0,tcp,http,SF,310,1881,0,0,0,0,...,255,1.0,0.0,0.01,0.05,0.00,0.01,0.0,0.0,normal
494016,0,tcp,http,SF,282,2286,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0,normal
494017,0,tcp,http,SF,203,1200,0,0,0,0,...,255,1.0,0.0,0.06,0.05,0.06,0.01,0.0,0.0,normal
494018,0,tcp,http,SF,291,1200,0,0,0,0,...,255,1.0,0.0,0.04,0.05,0.04,0.01,0.0,0.0,normal
494019,0,tcp,http,SF,219,1234,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0,normal

In [5]:
df['label'].value_counts()

attack    396743
normal     97277
Name: label, dtype: int64

In [6]:
df.isnull().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
attack                         0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
lnum_compromised               0
lroot_shell                    0
lsu_attempted                  0
lnum_root                      0
lnum_file_creations            0
lnum_shells                    0
lnum_access_files              0
lnum_outbound_cmds             0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
label                          0
dtype: int64

In [7]:
df2=pd.get_dummies(df.drop('label',axis=1))
df2

,duration,src_bytes,dst_bytes,attack,wrong_fragment,urgent,hot,num_failed_logins,logged_in,lnum_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0,181,5450,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1,0,239,486,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
2,0,235,1337,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,0,219,1337,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,217,2032,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494015,0,310,1881,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
494016,0,282,2286,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
494017,0,203,1200,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
494018,0,291,1200,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
494019,0,219,1234,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0

In [8]:
target=df['label'].map({'attack':0,'normal':1,'no':3})
target

0         1
1         1
2         1
3         1
4         1
         ..
494015    1
494016    1
494017    1
494018    1
494019    1
Name: label, Length: 494020, dtype: int64

In [9]:
X=df2.copy()

In [10]:
y=target.copy()

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
train_x, test_x, train_y, test_y=train_test_split(X,y,test_size=0.4,random_state=4)

model=RandomForestClassifier()
model.fit(train_x, train_y)
y_pred=model.predict(test_x)
cm=confusion_matrix(test_y, y_pred)
acc=accuracy_score(test_y, y_pred)
print(cm)
print(acc)
print("No. of failed cases- ",(test_y!=y_pred).sum())

[[158415     28]
 [    11  39154]]
0.9998026395692482
No. of failed cases-  39